BEGIN;
ALTER TABLE gmaps_jobs ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE gmaps_jobs ADD COLUMN worker_id TEXT DEFAULT '';
ALTER TABLE gmaps_jobs ADD COLUMN attempts INT DEFAULT 0;
COMMIT;
